plugins {
    id "java"
    id "dev.architectury.loom" version "1.11-SNAPSHOT" apply false
    id "architectury-plugin" version "3.4-SNAPSHOT"
    id 'com.gradleup.shadow' version '8.3.6' apply false
}

architectury {
    minecraft = project.properties.minecraft_version
}

allprojects {
    group "org.eu.awesomekalin.jta"
    version rootProject.properties.version
}

subprojects {
    apply plugin: 'dev.architectury.loom'   // Ensure Loom plugin is applied
    apply plugin: 'architectury-plugin'

    repositories {
        flatDir { dirs "../libs" }
        maven { url "https://repo.codemc.org/repository/maven-public" }
        maven { url = "https://maven.terraformersmc.com/" }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.properties.minecraft_version}"
        mappings loom.layered {
            it.mappings("net.fabricmc:yarn:$yarn_mappings:v2")
            it.mappings("dev.architectury:yarn-mappings-patch-neoforge:$yarn_mappings_patch_neoforge_version")
        }
        implementation "mtr:mtr-common:${rootProject.properties.mtr_version}"
    }

    java {
        withSourcesJar()
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }
}
