package org.eu.awesomekalin.jta.mod.init;

import org.eu.awesomekalin.jta.mod.Init;
import org.eu.awesomekalin.jta.mod.blocks.directional.roundel.RoundelBase;
import org.eu.awesomekalin.jta.mod.blocks.directional.roundel.RoundelPoleBase;
import org.eu.awesomekalin.jta.mod.blocks.directional.roundel.RoundelSignBase;
import org.eu.awesomekalin.jta.mod.blocks.directional.roundel.RoundelSmallSignBase;
import org.mtr.mapping.holder.Block;
import org.mtr.mapping.holder.Identifier;
import org.mtr.mapping.registry.BlockRegistryObject;

public class RoundelInit {
    public static final BlockRegistryObject ROUNDEL_BUSES = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/buses/buses_roundel"), () -> new Block(new RoundelBase("BUSES")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_COACHES = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/coaches/coaches_roundel"), () -> new Block(new RoundelBase("COACHES")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_DLR = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/dlr/dlr_roundel"), () -> new Block(new RoundelBase("DLR")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_ELIZEBETH = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/elizebeth/elizebeth_roundel"), () -> new Block(new RoundelBase("ELIZEBETH")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_NLE = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/nle/nle_roundel"), () -> new Block(new RoundelBase("UNDERGROUND")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_OVERGROUND = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/overground/overground_roundel"), () -> new Block(new RoundelBase("OVERGROUND")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_PRIDE = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/pride/pride_roundel"), () -> new Block(new RoundelBase("UNDERGROUND")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_RIVER = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/river/river_roundel"), () -> new Block(new RoundelBase("RIVER")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_TFL = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/tfl/tfl_roundel"), () -> new Block(new RoundelBase("TFL RAIL")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_TRAMS = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/trams/trams_roundel"), () -> new Block(new RoundelBase("TRAMS")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_UNDERGROUND = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/underground/underground_roundel"), () -> new Block(new RoundelBase("UNDERGROUND")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_POLE_BUSES = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/buses/buses_roundel_pole"), () -> new Block(new RoundelPoleBase("BUSES")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_POLE_COACHES = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/coaches/coaches_roundel_pole"), () -> new Block(new RoundelPoleBase("COACHES")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_POLE_DLR = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/dlr/dlr_roundel_pole"), () -> new Block(new RoundelPoleBase("DLR")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_POLE_ELIZEBETH = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/elizebeth/elizebeth_roundel_pole"), () -> new Block(new RoundelPoleBase("ELIZEBETH")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_POLE_NLE = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/nle/nle_roundel_pole"), () -> new Block(new RoundelPoleBase("NLE")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_POLE_OVERGROUND = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/overground/overground_roundel_pole"), () -> new Block(new RoundelPoleBase("OVERGROUND")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_POLE_PRIDE = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/pride/pride_roundel_pole"), () -> new Block(new RoundelPoleBase("PRIDE")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_POLE_RIVER = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/river/river_roundel_pole"), () -> new Block(new RoundelPoleBase("RIVER")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_POLE_TFL = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/tfl/tfl_roundel_pole"), () -> new Block(new RoundelPoleBase("TFL RAIL")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_POLE_TRAMS = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/trams/trams_roundel_pole"), () -> new Block(new RoundelPoleBase("TRAMS")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_POLE_UNDERGROUND = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/underground/underground_roundel_pole"), () -> new Block(new RoundelPoleBase("UNDERGROUND")), CreativeTabInit.JTA_ROUNDELS);

    public static final BlockRegistryObject ROUNDEL_SMALL_BUSES = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/buses/buses_roundel_small"), () -> new Block(new RoundelSmallSignBase("BUSES")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SMALL_COACHES = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/coaches/coaches_roundel_small"), () -> new Block(new RoundelSmallSignBase("COACHES")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SMALL_DLR = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/dlr/dlr_roundel_small"), () -> new Block(new RoundelSmallSignBase("DLR")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SMALL_ELIZEBETH = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/elizebeth/elizebeth_roundel_small"), () -> new Block(new RoundelSmallSignBase("ELIZEBETH")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SMALL_NLE = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/nle/nle_roundel_small"), () -> new Block(new RoundelSmallSignBase("NLE")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SMALL_OVERGROUND = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/overground/overground_roundel_small"), () -> new Block(new RoundelSmallSignBase("OVERGROUND")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SMALL_PRIDE = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/pride/pride_roundel_small"), () -> new Block(new RoundelSmallSignBase("UNDERGROUND")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SMALL_RIVER = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/river/river_roundel_small"), () -> new Block(new RoundelSmallSignBase("RIVER")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SMALL_TFL = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/tfl/tfl_roundel_small"), () -> new Block(new RoundelSmallSignBase("TFL RAIL")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SMALL_TRAMS = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/trams/trams_roundel_small"), () -> new Block(new RoundelSmallSignBase("TRAMS")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SMALL_UNDERGROUND = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/underground/underground_roundel_small"), () -> new Block(new RoundelSmallSignBase("UNDERGROUND")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SIMPLE_BUSES = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/buses/buses_roundel_simple"), () -> new Block(new RoundelSignBase("BUSES")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SIMPLE_COACHES = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/coaches/coaches_roundel_simple"), () -> new Block(new RoundelSignBase("COACHES")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SIMPLE_DLR = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/dlr/dlr_roundel_simple"), () -> new Block(new RoundelSignBase("DLR")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SIMPLE_ELIZEBETH = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/elizebeth/elizebeth_roundel_simple"), () -> new Block(new RoundelSignBase("ELIZEBETH")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SIMPLE_NLE = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/nle/nle_roundel_simple"), () -> new Block(new RoundelSignBase("NLE")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SIMPLE_OVERGROUND = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/overground/overground_roundel_simple"), () -> new Block(new RoundelSignBase("OVERGROUND")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SIMPLE_PRIDE = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/pride/pride_roundel_simple"), () -> new Block(new RoundelSignBase("PRIDE")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SIMPLE_RIVER = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/river/river_roundel_simple"), () -> new Block(new RoundelSignBase("RIVER")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SIMPLE_TFL = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/tfl/tfl_roundel_simple"), () -> new Block(new RoundelSignBase("TFL RAIL")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SIMPLE_TRAMS = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/trams/trams_roundel_simple"), () -> new Block(new RoundelSignBase("TRAMS")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject ROUNDEL_SIMPLE_UNDERGROUND = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/underground/underground_roundel_simple"), () -> new Block(new RoundelSignBase("UNDERGROUND")), CreativeTabInit.JTA_ROUNDELS);
    // Wall Roundels
    public static final BlockRegistryObject WALL_ROUNDEL_BUSES = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/buses/buses_wall_roundel"), () -> new Block(new RoundelBase("BUSES")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject WALL_ROUNDEL_COACHES = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/coaches/coaches_wall_roundel"), () -> new Block(new RoundelBase("COACHES")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject WALL_ROUNDEL_DLR = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/dlr/dlr_wall_roundel"), () -> new Block(new RoundelBase("DLR")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject WALL_ROUNDEL_ELIZEBETH = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/elizebeth/elizebeth_wall_roundel"), () -> new Block(new RoundelBase("ELIZEBETH")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject WALL_ROUNDEL_NLE = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/nle/nle_wall_roundel"), () -> new Block(new RoundelBase("UNDERGROUND")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject WALL_ROUNDEL_OVERGROUND = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/overground/overground_wall_roundel"), () -> new Block(new RoundelBase("OVERGROUND")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject WALL_ROUNDEL_PRIDE = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/pride/pride_wall_roundel"), () -> new Block(new RoundelBase("UNDERGROUND")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject WALL_ROUNDEL_RIVER = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/river/river_wall_roundel"), () -> new Block(new RoundelBase("RIVER")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject WALL_ROUNDEL_TFL = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/tfl/tfl_wall_roundel"), () -> new Block(new RoundelBase("TFL RAIL")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject WALL_ROUNDEL_TRAMS = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/trams/trams_wall_roundel"), () -> new Block(new RoundelBase("TRAMS")), CreativeTabInit.JTA_ROUNDELS);
    public static final BlockRegistryObject WALL_ROUNDEL_UNDERGROUND = Init.REGISTRY.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "roundel/generated/underground/underground_wall_roundel"), () -> new Block(new RoundelBase("UNDERGROUND")), CreativeTabInit.JTA_ROUNDELS);
    public static void INIT() {
        Init.LOGGER.debug("Registering JTA Roundels");
    }
}
